## Code Setup
Start any piece of Python coding by importing packages you make need. In this Project, we will use the Python pandas library

In [168]:
### Import the pandas library here 

import pandas as pd

Next, set your working directory. This is the location where all of your data files and Python coding files "live" for any project so that the computer understands what files to reference. In Jupyter Notebooks in Anaconda Cloud, your files can be uploaded in the environment on the left side of the screen.

## Importing Data

Next, read in the data file you want to use in your data analysis. Use the `pd.read_csv()` function from the pandas library to read in your CSV. **IMPORTANT**: Reading in CSVs is better than Excel. Why? CSVs do not have complicated formatting that Python will try to interpret.

In [173]:
### Read in your Nebraska data and assign it to a new dataframe

nebraska_data = pd.read_csv('Nebraska_Violations_Formatted.csv')

We may also want to make sure that the new data set we imported is a **dataframe**. Dataframes are a type of data structure in Python where each column is interpreted as a different variable that can then be manipulated. If we want to coerce a data set into a data frame, we can use the following syntax. Note that this syntax overwrites the *nebraska_data* we created above! Also, the `pd.` before the function tells Python that this function comes from the pandas package.

In [176]:
### Make sure the data is a dataframe using pd.DataFrame() function

nebraska_data = pd.DataFrame(nebraska_data)

Next, we can use the `print()` function to examine what types of data are present in our CSV. This gives us a chance to examine what types of data are present and what variables we will be able to manipulate.  We also always want to check that our data has been imported correctly.  `print()` prints out the first 5 and last 5 lines of the dataset for us so we can check.

In [179]:
## Print out your verified dataframe

print(nebraska_data)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

We may also want to look at a couple of other characteristics of our data.  `.head()` prints out the first 5 rows of the dataframe, and `.tail()` prints out the last 5 rows o the dataframe.  Let's try those function below on our `nebraska_data`  Both of these function are **appended** to a dataframe.  This means we start with the dataframe and use `.head()` to append the `head()` function to `nebraska_data`.  If we want to get the first ten rows of the dataframe, 10 can be added to the `.head()` function inside the parentheses as an **argument**.  If no arguments are added to a function, Python assumes you want the default arguments for a function.  For now, we don't need to worry all that much about arguments, but it is something we will need to think about later!

In [182]:
### Use the .head() function to view the first 10 rows of the data

nebraska_data.head(10)

,pws_id,pws_name,epa_region_code,primacy_agency,pws_type,owner_type,primary_source,activity_status,season_end_date,population,...,season_start_date,last_reported,submission_quarter,return_to_compliance_date,contaminant_code,submission_year,major_violation,connections,first_reported,submission_year.1
0,NE3120835,LITTLE USA,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,200,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
1,NE3121452,ELKHORN SHORES,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,35,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
2,NE3121245,DRIFTWOOD INN,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,25,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
3,NE3150475,TYSON FRESH MEATS INC MADISON,Region 7,Nebraska,NTNCWS,State,Ground water,Active,NaN,1100,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
4,NE3121401,SANDY POINTE LAKE DEVELOPMENT,Region 7,Nebraska,CWS,State,Ground water,Active,NaN,100,...,45139,45169.0,Known,NaN,SIF,State Public Notification received,Y,NaN,3,45244
5,NE3150672,FORT HARTSUFF SHP - NG & PC,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,45,...,45139,45169.0,Returned to Compliance,45188.0,SOX,State Compliance achieved,Y,NaN,3,45244
6,NE3101910,"SHELTON, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,1059,...,45139,45169.0,Known,NaN,SIE,State Public Notification requested,Y,NaN,3,45244
7,NE3150566,SARPY CO DIST 46 - PLATTEVIEW HIGH,Region 7,Nebraska,NTNCWS,State,Ground water,Active,NaN,614,...,45139,45169.0,Known,NaN,SIE,State Public Notification requested,Y,NaN,3,45244
8,NE3103105,"WOOD LAKE, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,70,...,45108,NaN,Returned to Compliance,45134.0,SOX,State Compliance achieved,NaN,NaN,3,45244
9,NE3120840,EAGLES NEST ESTATES,Region 7,Nebraska,CWS,State,Ground water,Active,NaN,52,...,45108,45199.0,Known,NaN,NaN,NaN,NaN,NaN,2,45244

In [184]:
### Use the .tail() function to view the bottom of the data 
nebraska_data.tail()

,pws_id,pws_name,epa_region_code,primacy_agency,pws_type,owner_type,primary_source,activity_status,season_end_date,population,...,season_start_date,last_reported,submission_quarter,return_to_compliance_date,contaminant_code,submission_year,major_violation,connections,first_reported,submission_year.1
12718,NE3117308,"PENDER, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,1100,...,28444,28473.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12719,NE3115902,"GOEHNER, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,185,...,28422,28452.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12720,NE3115905,"SEWARD, CITY OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,7500,...,28412,28442.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12721,NE3105907,"MILLIGAN, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,244,...,28321,28351.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12722,NE3115503,"CERESCO, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,919,...,28298,28327.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494

One other key thing we may want to check in our data is what columns we have.  In a Python dataframe, a column can be manipulated as a **variable**, which is very important because this means we can add, subtract, change, etc. our columns all at once instead of individually.  Let's practice the terms we used above: we want to **append** the `.columns` **function** to the `nebraska_data` **dataframe** and use the default **arguments**.  Note here that `.columns` does not have parentheses.  Why?  Because `.columns` is actually an indexer; only functions have () and arguments.

In [187]:
### Use the .column indexer to view the column names

nebraska_data.columns

Index(['pws_id', 'pws_name', 'epa_region_code', 'primacy_agency', 'pws_type',
       'owner_type', 'primary_source', 'activity_status', 'season_end_date',
       'population', 'rule_name', 'violation_code', 'violation_type',
       'violation_category', 'health_based', 'contaminant',
       'season_start_date', 'last_reported', 'submission_quarter',
       'return_to_compliance_date', 'contaminant_code', 'submission_year',
       'major_violation', 'connections', 'first_reported',
       'submission_year.1'],
      dtype='object')

There we go!  We have our data imported and we can quickly use functions like `print()` and indexers like `.columns` to check that everything looks correct and verify what variables we have to work with.

## Summarizing Data

Next, let's look at how to group data.  This is an important skill when you want to examine data in a final table that summarizes a statistic or characterisitic of your data.

1.) Append `.groupby()` to the end of a variable and then use square brackets [] and list the columns you want to group by

2.) Then, add `.size()` to the end of the statement to show the number of observations in each group

3.) Use `print` to show this new dataframe

In [192]:
### Group the nebraska_data by PWS Type and Contaminant
nebraska_data.groupby(['pws_type','contaminant']).size()
## Print the new grouped data 
print(nebraska_data)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

Now, we may want to use the data we just generated in future analyses. Therefore, we need to save that data to a variable. We will add `.reset_index(name = '')` to the end of the previous code and put the name of the new column  within the quote marks. We will assign this new dataframe to a dataframe called summary and then print the results.

This code will give us the number of violatnsio a for each contaminant by the type of water system

In [195]:
## Create the new data summary
nebraska_summary = nebraska_data.groupby(['pws_type','contaminant']).size().reset_index(name = 'n')
## Print the new data summary
print(nebraska_summary)
nebraska_summary.to_csv('contaminants in water.csv', index=False)

    pws_type                                        contaminant    n
0        CWS                              1,1,1-Trichloroethane   10
1        CWS                              1,1,2-Trichloroethane    4
2        CWS                               1,1-Dichloroethylene   10
3        CWS                             1,2,4-Trichlorobenzene   10
4        CWS                        1,2-DIBROMO-3-CHLOROPROPANE    2
..       ...                                                ...  ...
113    TNCWS                                            Nitrate   23
114    TNCWS                                    Nitrate-Nitrite  508
115    TNCWS                                      Public Notice  213
116    TNCWS                        Revised Total Coliform Rule  376
117    TNCWS  Stage 1 Disinfectants and Disinfection Byprodu...    6

[118 rows x 3 columns]

The code above only summarizes the total number of violations.  What if we want to know some more in depth statistics about this data?  

The function `.agg()` is a pandas function that aggregates data.  Note that because it is a pandas function, `.agg()` will only work if you have imported the correct packages!  

`.agg()` can take arguments such as max, min, mean and median.  In order for this function to work, you need to tell `.agg()` which summary statistic you want (for example `max()`) and then tell the statistic what to take the statistic of and what you want that new data column to be called.  For example, if we want to take the max() of the column "violations" and name this new data column "maximum", our code would look like this:
`.agg(max('violations', 'maximum')`

Try this out using your summary data, group by contaminant and assign this new summary statistic data to a data frame called `stat_summary`and print this new dataframe to the console.

In [198]:
## Create the statistical summary using the .agg() function
stat_summary = nebraska_summary.groupby('contaminant').agg(max=('n','max'),
                                                           min=('n','max'),
                                                           mean=('n','mean'),
                                                           median=('n','median'))
## Print the new statistical summary 
print(stat_summary)

                             max  min  mean  median
contaminant
1,1,1-Trichloroethane         10   10  10.0    10.0
1,1,2-Trichloroethane          4    4   4.0     4.0
1,1-Dichloroethylene          10   10  10.0    10.0
1,2,4-Trichlorobenzene        10   10  10.0    10.0
1,2-DIBROMO-3-CHLOROPROPANE    2    2   2.0     2.0
...                          ...  ...   ...     ...
Xylenes, Total                 8    8   8.0     8.0
cis-1,2-Dichloroethylene       4    4   4.0     4.0
o-Dichlorobenzene             10   10  10.0    10.0
p-Dichlorobenzene             10   10  10.0    10.0
trans-1,2-Dichloroethylene    10   10  10.0    10.0

[85 rows x 4 columns]

What if we wanted to group by a different column? How would the code look different if you wanted to look at the type of water system instead of the contaminant name?

In [201]:
## Try a new statistical summary using the type of water system. Print the new statistical summary 
stat_summary = nebraska_summary.groupby('pws_type').agg(max=('n','max'),
                                                                    min=('n','max'),
                                                                    mean=('n','mean'),
                                                                    median=('n','median'))

print(stat_summary)
stat_summary.to_csv('violations.csv', index=False)

           max   min        mean  median
pws_type
CWS       5348  5348  103.423529    10.0
NTNCWS     315   315   29.041667     1.0
TNCWS     2059  2059  359.444444    29.0

Now we will analyze violations in Nebraska’s public water systems by calculating the percentage of total violations each PWS type accounts for per contaminant. Using `groupby` and `size`, we first counted violations for each combination of PWS type and contaminant (this is the same summary as above). We then applied `groupby` and `sum` to compute the total violations per contaminant before merged this total back into the summary using `merge`. To determine each PWS type's contribution, we calculated the percentage by dividing individual counts by the total. Finally, we used `pivot` to restructure the table for better readability, making it easier to compare contaminant distribution among the three water systems.
Take a look at both summaries generated by the print function to gain insight into what `pivot` can offer.

In [204]:

## First using create a summary for PWS type and Contaminant using the .grouby .size() and .reset_index
summary = nebraska_data.groupby(['pws_type','contaminant']).size().reset_index(name = 'n')

## Now calculate the total violations per contaminant using .sum() 
total_per_contaminant = summary.groupby('contaminant')['n'].sum().reset_index(name='total')

## Now merge the total violations per contaminat back to the summary created in first step. Use the .merge()
summary = summary.merge(total_per_contaminant, on='contaminant')

## Now calculate the percentage of violations for each contaminant accounted for by each PWS type.
summary['percent_of_total'] = (summary['n']/summary['total'])*100
print(summary)

## Optional: Use .pivot to pivot the summary table and explore what table pivoting does
summary_pivot = summary.pivot(index = 'contaminant',columns = 'pws_type',values = 'percent_of_total')
print(summary_pivot)

## Exporting our summary_pivot to a csv
summary_pivot.to_csv('percentages.csv',index=False)
# Optional: pivot the table for better readability

    pws_type                  contaminant   n  total  percent_of_total
0        CWS        1,1,1-Trichloroethane  10     10             100.0
1        CWS        1,1,2-Trichloroethane   4      4             100.0
2        CWS         1,1-Dichloroethylene  10     10             100.0
3        CWS       1,2,4-Trichlorobenzene  10     10             100.0
4        CWS  1,2-DIBROMO-3-CHLOROPROPANE   2      2             100.0
..       ...                          ...  ..    ...               ...
113      CWS               Xylenes, Total   8      8             100.0
114      CWS     cis-1,2-Dichloroethylene   4      4             100.0
115      CWS            o-Dichlorobenzene  10     10             100.0
116      CWS            p-Dichlorobenzene  10     10             100.0
117      CWS   trans-1,2-Dichloroethylene  10     10             100.0

[118 rows x 5 columns]
pws_type                       CWS  NTNCWS  TNCWS
contaminant
1,1,1-Trichloroethane        100.0     NaN    NaN
1,1,2-Trichloroethane        100.0     NaN    NaN
1,1-Dichloroethylene         100.0     NaN    NaN
1,2,4-Trichlorobenzene       100.0     NaN    NaN
1,2-DIBROMO-3-CHLOROPROPANE  100.0     NaN    NaN
...                            ...     ...    ...
Xylenes, Total               100.0     NaN    NaN
cis-1,2-Dichloroethylene     100.0     NaN    NaN
o-Dichlorobenzene            100.0     NaN    NaN
p-Dichlorobenzene            100.0     NaN    NaN
trans-1,2-Dichloroethylene   100.0     NaN    NaN

[85 rows x 3 columns]

You'll notice above that the code does not need to change much in order to make big changes to the dataframe you are creating. This is why it is very important to name your dataframes in a descriptive way and keep track of what types of data you are manipulating

## Filtering Data

Next, let's examine how to filter data so that we only keep the observations relevant to our intended analysis.

First, we can filter our data by using indices and AND (&) or OR   (|) operators. Let's try filtering for only 'Active' systewa. The variable we want to index to filter is the 'activity_status' column name and the condition we want is only the columns with the string 'Active'. Therefore, we can write:

In [209]:
### Filter for only active systems using the indexing method
active_systems = nebraska_data[(nebraska_data['activity_status']=="Active")]

## Check that your code has done what it was supposed to using print, .head(), .tail(), or .column()
print(active_systems)
active_systems.head(10)
active_systems.tail(10)
active_systems.columns

active_systems.to_csv('active_systems.csv',index=False)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

Notice that the variable name (activity_status) and the string ('A') must both be in quotes.  We also use a double equals sign (==) when we are asking Python to find a specific case within a column.  A single equal sign (=) is used to assign new variables.

Also notice that we can print only the activity_status column by appending it to the dataframe as a way to check that we have properly filtered our data.

There are other methods that can be used to filter in Python.  For example, the function `df.query()` can be used to examine the number of active systems:

In [212]:
### Try the same filter as above but use the .query() methodac
active_systems_query = nebraska_data.query('activity_status=="Active"')
print(active_systems_query['activity_status'])

0        Active
1        Active
2        Active
3        Active
4        Active
          ...
12718    Active
12719    Active
12720    Active
12721    Active
12722    Active
Name: activity_status, Length: 12723, dtype: object

Now, what if we want to apply more than one filter?

What if we want active systems AND systems with a Maximum Contaminant Level Violation?
We can use the & sign to represent AND in Python. this means that if we want 'activity_status' == "Active AND also want 'violaton_type' == "Maximum Contaminant Level Violation, Average", then we would need to write the following:

In [215]:
## Try applying multiple filters to the nebraska dataset
subset0 = nebraska_data[(nebraska_data['activity_status']=="Active") & (nebraska_data['violation_type']=="Maximum Contaminant Level Violation, Average")]

print(subset0['violation_type'])

9        Maximum Contaminant Level Violation, Average
17       Maximum Contaminant Level Violation, Average
18       Maximum Contaminant Level Violation, Average
26       Maximum Contaminant Level Violation, Average
27       Maximum Contaminant Level Violation, Average
                             ...
12579    Maximum Contaminant Level Violation, Average
12580    Maximum Contaminant Level Violation, Average
12581    Maximum Contaminant Level Violation, Average
12582    Maximum Contaminant Level Violation, Average
12583    Maximum Contaminant Level Violation, Average
Name: violation_type, Length: 1583, dtype: object

You may notice that there are two different ways that an MCL violation is reported: as an average sample or as a single sample.  If we don't care about the distinction in our analysis, we would want to include both so we do not exclude relevant data for our client.  This means that we would want to filter for "Maximum Contaminant Level, Average" OR "Maximum Contaminant Level, Single Sample"  To represent OR when filtering, use the `|` symbol.  Let's repeat our code from above but add in the OR statement.

In [218]:
## Apply the multiple filters 

subset1 = nebraska_data[(nebraska_data['activity_status']=="Active") & 
(nebraska_data['violation_type']=="Maximum Contaminant Level Violation, Average")|
(nebraska_data['violation_type']=="Maximum Contaminant Level Violation, Single Sample")]

## Print only the column 'violation_type'
print(subset1['violation_type'])

# Trying to extract the subset to CSV to visualize the columns
subset1.to_csv('subset1.csv', index = False)

9             Maximum Contaminant Level Violation, Average
12       Maximum Contaminant Level Violation, Single Sa...
13       Maximum Contaminant Level Violation, Single Sa...
14       Maximum Contaminant Level Violation, Single Sa...
15       Maximum Contaminant Level Violation, Single Sa...
                               ...
12718    Maximum Contaminant Level Violation, Single Sa...
12719    Maximum Contaminant Level Violation, Single Sa...
12720    Maximum Contaminant Level Violation, Single Sa...
12721    Maximum Contaminant Level Violation, Single Sa...
12722    Maximum Contaminant Level Violation, Single Sa...
Name: violation_type, Length: 2664, dtype: object

## Combining, Grouping, Filtering, and Summary Statistics

Now, let's combine the concepts we've learned to try and answer a question from our client.

Our client wants to look at only small systems serving less than 10000 people, only wants to look at active systems and wants to know the total number of violations occurring in Iowa categorized by the type of water system, the source water type and contaminant.  Let's break down this word problem into coding steps:
1.) To look for only small systems, we will need to apply a filter that states a population_served >= 10000
2.) To look for only active systems, we will need to apply a filter that states activity_status = "Active"
3.) To have a table the categorizes by system type, source water type and contaminant we need to group by pws_type, primary_source and contaminant_name respectively
4.) To find the sum of violations, we need to use the `.agg()` function and look up a function that will take the sum of a column


Let's put this all together in the code below:

In [221]:
## Step 1 & 2: filter based on activity status and population
subset2 = nebraska_data[(nebraska_data['activity_status']=="Active") & 
(nebraska_data['population'] <=10000)]

## Step 3: get violations for type of water systems, source, and contaminant
subset2_group = subset2.groupby(['pws_type','primary_source','contaminant']).size().reset_index(name = 'n')

## Step 4: calculate sum of violations
subset2_sum = subset2_group.groupby(['pws_type','primary_source','contaminant']).agg(sum=('n','sum'))


print(subset2_sum)

                                                                                         sum
pws_type primary_source                                     contaminant
CWS      Ground water                                       1,1,1-Trichloroethane         10
                                                            1,1,2-Trichloroethane          4
                                                            1,1-Dichloroethylene           9
                                                            1,2,4-Trichlorobenzene        10
                                                            1,2-DIBROMO-3-CHLOROPROPANE    2
...                                                                                      ...
TNCWS    Purchased ground water under influence of surfa... Public Notice                  5
                                                            Revised Total Coliform Rule    4
         Surface water purchased                            Coliform (TCR)                82
                                                            Public Notice                  3
                                                            Revised Total Coliform Rule   18

[168 rows x 1 columns]

In [223]:
# define a function called "categorize(x) that takes in the column of data population
# output a category for each based on population size conditions

# Step1: Define a function.
# In python, functions should always be defined prior to using it 

def categorize(x): 
    if x<1000: 
        return "small"
    elif 1000<=x<=10000:
        return "medium"
    else:
        return "large"

# Apply function to population to create a pop_category variable 

nebraska_data['pop_category'] = nebraska_data['population'].apply(categorize)

print(nebraska_data['pop_category'])

#Filter data based on small population
small_pop_data = nebraska_data[nebraska_data['pop_category'] =="small"]

print(small_pop_data)
small_pop_data.to_csv('small pop data1.csv', index=False)

0         small
1         small
2         small
3        medium
4         small
          ...
12718    medium
12719     small
12720    medium
12721     small
12722     small
Name: pop_category, Length: 12723, dtype: object
          pws_id                       pws_name epa_region_code  \
0      NE3120835                     LITTLE USA        Region 7
1      NE3121452                 ELKHORN SHORES        Region 7
2      NE3121245                  DRIFTWOOD INN        Region 7
4      NE3121401  SANDY POINTE LAKE DEVELOPMENT        Region 7
5      NE3150672    FORT HARTSUFF SHP - NG & PC        Region 7
...          ...                            ...             ...
12716  NE3114104            LINDSAY, VILLAGE OF        Region 7
12717  NE3114103              HUMPHREY, CITY OF        Region 7
12719  NE3115902            GOEHNER, VILLAGE OF        Region 7
12721  NE3105907           MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503            CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
5           Nebraska    TNCWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12716       Nebraska      CWS      State   Ground water          Active
12717       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... last_reported      submission_quarter  \
0                  NaN         200  ...       45199.0                   Known
1                  NaN          35  ...       45199.0                   Known
2                  NaN          25  ...       45199.0                   Known
4                  NaN         100  ...       45169.0                   Known
5                  NaN          45  ...       45169.0  Returned to Compliance
...                ...         ...  ...           ...                     ...
12716              NaN         255  ...       28475.0                   Known
12717              NaN         842  ...       28475.0                   Known
12719              NaN         185  ...       28452.0                   Known
12721              NaN         244  ...       28351.0                   Known
12722              NaN         919  ...       28327.0                   Known

      return_to_compliance_date contaminant_code  \
0                           NaN              NaN
1                           NaN              NaN
2                           NaN              NaN
4                           NaN              SIF
5                       45188.0              SOX
...                         ...              ...
12716                       NaN              NaN
12717                       NaN              NaN
12719                       NaN              NaN
12721                       NaN              NaN
12722                       NaN              NaN

                          submission_year major_violation  connections  \
0                                     NaN               Y          NaN
1                                     NaN               Y          NaN
2                                     NaN               Y          NaN
4      State Public Notification received               Y          NaN
5               State Compliance achieved               Y          NaN
...                                   ...             ...          ...
12716                                 NaN             NaN          NaN
12717                                 NaN             NaN          NaN
12719                                 NaN             NaN          NaN
12721                                 NaN             NaN          NaN
12722                                 NaN             NaN          NaN

       first_reported submission_year.1  pop_category
0                   3             45244         small
1                   3             45244         small
2                   3             45244         small
4                   3             45244         small
5                   3             45244         small
...               ...               ...           ...
12716               2             29494         small
12717               2             29494         small
12719               2             29494         small
12721               2             29494         small
12722               2             29494         small

[11235 rows x 27 columns]

In [261]:
# Assign category 
def assign_category(x):
    if x<=500:
       return "very small"
    elif 501<=x<=3300:
       return "small"
    elif 3301<x<=10000:
       return "medium"
    elif 10001<=x<=100000:
       return "large"
    else: 
       return "very large"

#create a pop category
nebraska_data['population_category'] = nebraska_data['population'].apply(assign_category)
subset1 = nebraska_data[(nebraska_data['activity_status']=="Active")]
summary2 = subset1.groupby(['pws_type','contaminant','pop_category']).size().reset_index(name='quantity')

print(summary2)
summary2.to_csv('Final Summary Question02.csv',index=False)

    pws_type                                        contaminant pop_category  \
0        CWS                              1,1,1-Trichloroethane        small
1        CWS                              1,1,2-Trichloroethane        small
2        CWS                               1,1-Dichloroethylene        large
3        CWS                               1,1-Dichloroethylene        small
4        CWS                             1,2,4-Trichlorobenzene        small
..       ...                                                ...          ...
169    TNCWS                                            Nitrate        small
170    TNCWS                                    Nitrate-Nitrite        small
171    TNCWS                                      Public Notice        small
172    TNCWS                        Revised Total Coliform Rule        small
173    TNCWS  Stage 1 Disinfectants and Disinfection Byprodu...        small

     quantity
0          10
1           4
2           1
3           9
4          10
..        ...
169        23
170       508
171       213
172       376
173         6

[174 rows x 4 columns]

In [252]:


subset3 = nebraska_data[(nebraska_data['activity_status']=="Active") &
(nebraska_data['violation_type']== "Maximum Contaminant Level Violation, Single Sample") |
(nebraska_data['violation_type']== "Maximum Contaminant Level Violation, Average") |
(nebraska_data['violation_type']== "Maximum Contaminant Level Violation, E. coli (RTCR)") |
(nebraska_data['violation_type']== "Maximum Contaminant Level Violation, Monthly (TCR)") |
(nebraska_data['violation_type']== "Maximum Contaminant Level Violation, Acute (TCR)")]

summary3 = subset3.groupby(['primary_source', 'violation_type','pop_category','pws_type',"contaminant"]).size().reset_index(name='quantity')
summary4 = summary3[(summary3['pop_category']=="small")]
summary5 = summary4[(summary4['pws_type']=="CWS")]

print(summary5)

summary5.to_csv("Request4.csv", index=False)

                                   primary_source  \
3                                    Ground water
26                                   Ground water
27                                   Ground water
28                                   Ground water
29                                   Ground water
30                                   Ground water
31                                   Ground water
32                                   Ground water
33                                   Ground water
34                                   Ground water
35                                   Ground water
36                                   Ground water
37                                   Ground water
38                                   Ground water
47                                   Ground water
53                                   Ground water
63                                   Ground water
64                                   Ground water
65                                   Ground water
66                                   Ground water
67                                   Ground water
68                                   Ground water
69                                   Ground water
70                                   Ground water
71                                   Ground water
72                                   Ground water
79                         Ground water purchased
82                         Ground water purchased
83                         Ground water purchased
84                         Ground water purchased
85                         Ground water purchased
86                         Ground water purchased
87                         Ground water purchased
88                         Ground water purchased
89                         Ground water purchased
90                         Ground water purchased
92                         Ground water purchased
95                         Ground water purchased
96                         Ground water purchased
97                         Ground water purchased
98                         Ground water purchased
103  Groundwater under influence of surface water
113                       Surface water purchased
115                       Surface water purchased
116                       Surface water purchased
118                       Surface water purchased

                                        violation_type pop_category pws_type  \
3     Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
26        Maximum Contaminant Level Violation, Average        small      CWS
27        Maximum Contaminant Level Violation, Average        small      CWS
28        Maximum Contaminant Level Violation, Average        small      CWS
29        Maximum Contaminant Level Violation, Average        small      CWS
30        Maximum Contaminant Level Violation, Average        small      CWS
31        Maximum Contaminant Level Violation, Average        small      CWS
32        Maximum Contaminant Level Violation, Average        small      CWS
33        Maximum Contaminant Level Violation, Average        small      CWS
34        Maximum Contaminant Level Violation, Average        small      CWS
35        Maximum Contaminant Level Violation, Average        small      CWS
36        Maximum Contaminant Level Violation, Average        small      CWS
37        Maximum Contaminant Level Violation, Average        small      CWS
38        Maximum Contaminant Level Violation, Average        small      CWS
47   Maximum Contaminant Level Violation, E. coli (...        small      CWS
53   Maximum Contaminant Level Violation, Monthly (...        small      CWS
63   Maximum Contaminant Level Violation, Single Sa...        small      CWS
64   Maximum Contaminant Level Violation, Single Sa...        small      CWS
65   Maximum Contaminant Level Violation, Single Sa...        small      CWS
66   Maximum Contaminant Level Violation, Single Sa...        small      CWS
67   Maximum Contaminant Level Violation, Single Sa...        small      CWS
68   Maximum Contaminant Level Violation, Single Sa...        small      CWS
69   Maximum Contaminant Level Violation, Single Sa...        small      CWS
70   Maximum Contaminant Level Violation, Single Sa...        small      CWS
71   Maximum Contaminant Level Violation, Single Sa...        small      CWS
72   Maximum Contaminant Level Violation, Single Sa...        small      CWS
79    Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
82        Maximum Contaminant Level Violation, Average        small      CWS
83        Maximum Contaminant Level Violation, Average        small      CWS
84        Maximum Contaminant Level Violation, Average        small      CWS
85        Maximum Contaminant Level Violation, Average        small      CWS
86        Maximum Contaminant Level Violation, Average        small      CWS
87        Maximum Contaminant Level Violation, Average        small      CWS
88        Maximum Contaminant Level Violation, Average        small      CWS
89        Maximum Contaminant Level Violation, Average        small      CWS
90   Maximum Contaminant Level Violation, E. coli (...        small      CWS
92   Maximum Contaminant Level Violation, Monthly (...        small      CWS
95   Maximum Contaminant Level Violation, Single Sa...        small      CWS
96   Maximum Contaminant Level Violation, Single Sa...        small      CWS
97   Maximum Contaminant Level Violation, Single Sa...        small      CWS
98   Maximum Contaminant Level Violation, Single Sa...        small      CWS
103  Maximum Contaminant Level Violation, Monthly (...        small      CWS
113   Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
115       Maximum Contaminant Level Violation, Average        small      CWS
116       Maximum Contaminant Level Violation, Average        small      CWS
118  Maximum Contaminant Level Violation, Monthly (...        small      CWS

                         contaminant  quantity
3                     Coliform (TCR)       235
26                1,2-Dichloroethane         1
27                           Arsenic       180
28                           Benzene         5
29              Carbon tetrachloride         6
30   Combined Radium (-226 and -228)        24
31                  Combined Uranium       141
32        Di(2-ethylhexyl) phthalate         1
33                ETHYLENE DIBROMIDE         1
34    Gross Alpha, Excl. Radon and U        10
35                           Nitrate        47
36                   Nitrate-Nitrite       237
37                          Selenium        63
38               Tetrachloroethylene         1
47       Revised Total Coliform Rule        36
53                    Coliform (TCR)      2792
63                1,2-Dichloroethane         2
64                           Arsenic         3
65                           Benzene         1
66              Carbon tetrachloride         1
67                  Combined Uranium         6
68                ETHYLENE DIBROMIDE         2
69                          Fluoride         2
70                           Nitrate        23
71                   Nitrate-Nitrite       356
72                          Selenium        90
79                    Coliform (TCR)        34
82                1,2-Dichloroethane         1
83                           Arsenic        26
84   Combined Radium (-226 and -228)         1
85                  Combined Uranium       116
86    Gross Alpha, Excl. Radon and U         3
87                           Nitrate         6
88                   Nitrate-Nitrite        76
89               Tetrachloroethylene         3
90       Revised Total Coliform Rule         7
92                    Coliform (TCR)       444
95                1,2-Dichloroethane         1
96                           Nitrate         7
97                   Nitrate-Nitrite        64
98                          Selenium         2
103                   Coliform (TCR)         2
113                   Coliform (TCR)         2
115               ETHYLENE DIBROMIDE         1
116                             TTHM        44
118                   Coliform (TCR)        20